codecov:
  require_ci_to_pass: yes

coverage:
  precision: 1
  round: down
  range: "50...75"
  status:
    project:
      default:
        target: auto
        threshold: 2%
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch:
      default:
        target: auto
        threshold: 2%
        if_ci_failed: error
        informational: false
        only_pulls: false
