name: Codecov workflow
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        # Pydantic fix version until issues with BaseSettings are fixed
        run: |
          python -m pip install --upgrade pip
          python -m pip install ase cclib matplotlib numpy scipy ray
          python -m pip install umap-learn psutil bayesian-optimization qcelemental
          python -m pip install pydantic==1.10.11
          python -m pip install pandas
          python -m pip install pytest-cov
      - name: Run tests and collect coverage
        run: pytest --cov=mbgdml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
